### ISSUE TITLE
uBlock script decreasing quality

### ISSUE THREAD

**Issue by Pipole26** [pixeltris/TwitchAdSolutions#110] opened 2022-11-04 05:26 UTC
On Chrome it doesn't decrease quality (at least Ungoogled Chromium),

On Firefox, it does decrease to 480p until it blocks all ads. 

Is there any way to watch it full quality on Firefox too? 

Thank you.

**Comment by EldritchEevee** [comment] 2022-11-08 20:00
It's capped at 480p **on all browsers**.

**Comment by iraouf** [comment] 2022-11-11 04:00
share script pls

**Comment by Pipole26** [comment] 2022-11-14 08:24
> It's capped at 480p on all browsers.

As I said, not on Ungoogled Chromium.

> share script pls

Applying a script (uBlock Origin)

    Navigate to the uBlock Origin Dashboard (the extension options)
    Under the My filters tab add twitch.tv##+js(twitch-videoad).
    Under the Settings tab, enable I am an advanced user, then click the cog that appears. Modify the value of userResourcesLocation from unset to the full url of the solution you wish to use (if a url is already in use, add a space after the existing url). e.g. userResourcesLocation https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js
    To ensure uBlock Origin loads the script I recommend that you disable/enable the uBlock Origin extension (or restart your browser).

To stop using a script remove the filter and make the url unset

**Comment by Gundor** [comment] 2022-11-15 08:54
yep, at stucked on 480p too on firefox

**Comment by pixeltris** [comment] 2022-11-19 21:27
This was by design by the original maintainer of the extension to avoid freezing issues under Firefox. I'm closing this as I don't have plans of changing vaft.

**Closed by pixeltris** 2022-11-19 21:27 UTC
