### ISSUE TITLE
Ads bleeding through VAFT but not Video-Swap

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#244] opened 2024-04-27 15:25 UTC
I did not check if the script is loading appropriately or not, but it seems to selectively not load. That said Video-Swap works, but has no way to check latency.

**Comment by pixeltris** [comment] 2024-04-27 19:10
Duplicate of #241 and fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/02447140c7522721601ac62c4fb47c7757e054d7

**Closed by pixeltris** 2024-04-27 19:10 UTC
