### ISSUE TITLE
Does not work anymore ?.

### ISSUE THREAD

**Issue by Geant200** [pixeltris/TwitchAdSolutions#252] opened 2024-05-15 12:44 UTC
Good morning

I am creating the post to warn you that your script no longer works, the ads are visible again and are no longer blocked.

An update is necessary I think?

I thank you in advance.

**Comment by filipemanuelofs** [comment] 2024-05-16 17:47
Same.. I was getting ads with `vaft`. I changed to `video-swap-new` and it stopped.

**Comment by revunix** [comment] 2024-05-16 23:01
I seriously wonder how many more topics will be opened here on this subject. We know by now that this script no longer works properly...

**Comment by Geant200** [comment] 2024-05-31 12:45
For my part it's good, it's back to normal, thank you for the changes.

**Comment by evilmaran** [comment] 2024-05-31 14:47
> Lets get some extra info again, what browser are you guys and what extensions are you using? Do you see any references to `ads` in your browser console?(hit F12 and filter console output to "ads"). If not, the scripts are potentially NOT loading correctly.
> 
> ![Screenshot 2024-05-30 200317](https://private-user-images.githubusercontent.com/10717304/335407452-8d17d350-0339-4d90-b495-dcaa005a6212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjYxNjAsIm5iZiI6MTcxNzE2NTg2MCwicGF0aCI6Ii8xMDcxNzMwNC8zMzU0MDc0NTItOGQxN2QzNTAtMDMzOS00ZDkwLWI0OTUtZGNhYTAwNWE2MjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE0MzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYjRjMWI3MDQ5MGQwZWRiN2RiNDc4ODRjMWFkMDQ5Yzk5ZjA3M2UyZTEyOTc5MmUxMDhiYzg0NmI5MGRkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IWo-bUyJN-DHL5OJCGv4TX5QNLauxyJmWRYs7iUozpI)
> 
> ![image](https://private-user-images.githubusercontent.com/10717304/335407347-413dc688-e989-4637-b6fa-ca569169088e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjYxNjAsIm5iZiI6MTcxNzE2NTg2MCwicGF0aCI6Ii8xMDcxNzMwNC8zMzU0MDczNDctNDEzZGM2ODgtZTk4OS00NjM3LWI2ZmEtY2E1NjkxNjkwODhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE0MzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxOTdmMTgwMDAwMmQ4NzRlYjUyOGVkYWY4OTNmNWE5MzkyZDYxMWM0YzFhMDQyMTJiYTdmZmQzN2IwMjRjOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jpuRqHNQQJb6y70HP1tZYC1wdy35Zg1pbQa_TKG4R0Q)
> 
> If you have any chat related extensions/addons, like FFZ or BetterTTV, they shouldn't conflict with the scripts here but you can try disabling those. If you have other twitch ad-block solutions like TTV LOL Pro that are proxy based, try disabling that and using only the `vaft` or `video-swap-new` scripts. Double check the `userResourceLocation` URL is set correctly if you are using uBlock Origin to apply the scripts. uBo has some known issues(#200) with the scripts so try the userscript versions instead. Be sure to clear your uBo setup by removing the filter and making the url `unset` ![Screenshot 2024-05-30 201752](https://private-user-images.githubusercontent.com/10717304/335408013-cc735d50-d68f-4094-bb45-e771057e60d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjYxNjAsIm5iZiI6MTcxNzE2NTg2MCwicGF0aCI6Ii8xMDcxNzMwNC8zMzU0MDgwMTMtY2M3MzVkNTAtZDY4Zi00MDk0LWJiNDUtZTc3MTA1N2U2MGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE0MzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMWQzYjljYjgzYmQwYTg5YzNjZTViMTExOGE0MDQ0MmEzYzNmMjlhNDM2NzFmNzJhYWE4N2NiODRmNGM0NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLFrhT0G9bMTQpbymyzsQSe4HUXg9tvB8drkYj6Cg4Y)


Most issues have been resolved, sometimes loading/buffering seems to take longer, also would like some clarification on if other extensions (like FFZ, 7TV, alternate player) interfere with the scripts, should i be running only vaft or can i run both vaft and video-swap-new?

When i pull up console i do see some ads references like:
`<link href="data:text/css,%3Ais(%5Bid*%3D'google_ads_iframe'%5D%2C%5Bid*%3D'taboola-'%5D%2C.taboolaHeight%2C.taboola-placeholder%2C%23credential_picker_container%2C%23credentials-picker-container%2C%23credential_picker_iframe%2C%5Bid*%3D'google-one-tap-iframe'%5D%2C%23google-one-tap-popup-container%2C.google-one-tap-modal-div%2C%23amp_floatingAdDiv%2C%23ez-content-blocker-container)%20%7Bdisplay%3Anone!important%3Bmin-height%3A0!important%3Bheight%3A0!important%3B%7D" rel="stylesheet" type="text/css">`

Using Firefox and some other twitch extensions like 7TV and FFZ, also use "Alternate Player for Twitch" sometimes but only when Twitch get super annoying with ads and even then Alternate Player doesnt always get rid of ads anymore.
Vaft and video-swap-new scripts are loaded with Greasemonkey.
And ofcourse Ublock Origin is always running, with some added filters for YouTube.

**Comment by stevenya97** [comment] 2024-06-01 00:37
@evilmaran twitch player/chat extensions should be fine. I'm running FFZ and no issues. You should have only one ad block solution active, so either `vaft` or `video-swap-new` active not both. They both monitor the m3u8 video stream so they can conflict with each other

**Comment by evilmaran** [comment] 2024-06-03 13:53
> @evilmaran twitch player/chat extensions should be fine. I'm running FFZ and no issues. You should have only one ad block solution active, so either `vaft` or `video-swap-new` active not both. They both monitor the m3u8 video stream so they can conflict with each other. You can keep both in greasemonkey just have only one active. You can swap between them if having issues. This extends to other extensions as well that offer ad block capabilities. For example `Adguard Extra` includes Twitch adblocking that is similar to vaft, if you use that I'd exclude twitch.tv from it

*****************

Gave it a few days, but seems with vaft script i do get ads, but with video-swap-new it seems to be fine.

**Comment by evilmaran** [comment] 2024-06-04 09:01
think i found the problem: Source map error: Error: URL constructor:  is not a valid URL.
Resource URL: user-script:https%3A//github.com/pixeltris/TwitchAdSolutions/TwitchAdSolutions%20%28vaft%29
Source Map URL: null

seems the userResourcesLocation url got updated and i forgot to do that in my ublock settings, must have missed that last time...

**Comment by xunkar** [comment] 2024-06-04 17:19
I'm using Firefox and video-swap-new via uBlock Origin, no other browser extension beside FFZ, and when ads are playing there are 0 messages in the console mentioning ads, things were working fine until recently. I've tried clearing cache to no avail.

**Comment by stevenya97** [comment] 2024-06-04 23:57
@evilmaran I see in your edit that you are getting the banner now? Does this mean it works now? The 360p stream is intended behavior. The script stitches the live stream preview(only stream currently that doesn't have ads embedded in them) that twitch sometimes places above chat during ads with the clean audio feed together. It should jump back to full quality after the ad is over.

**Comment by evilmaran** [comment] 2024-06-05 00:00
yes it seems to be working, still have those errors in console logs...

now to figure out what happened with youtube and reddit....

**Comment by stevenya97** [comment] 2024-06-05 00:01
@xunkar Under the `My filters` tab in the uBlock dashboard, did you add `twitch.tv##+js(twitch-videoad)`? If you are not seeing any messages in the console then the script is not being loaded for some reason. First step would be to double check your config. Perhaps the link to the script needs to be updated on your end?

**Comment by stevenya97** [comment] 2024-06-05 01:39
@evilmaran It is just a warning label(yellow not critical red) so as long as sites function correctly you can ignore them. It might be CORS or Enhanced Tracking Protection related depending on how you have your Firefox setup. Youtube and Reddit are outside the scope of this thread but you can ask on [r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/) or [r/Firefox](https://www.reddit.com/r/firefox/) if you want other opinions. You can also research CORS for details but most likely those domains are throwing a warning for security/anti-tracking purposes by Firefox. That last `edge.ads.twitch.tv` message indicates that the page ad was blocked

**Comment by xunkar** [comment] 2024-06-05 21:52
> @xunkar Under the `My filters` tab in the uBlock dashboard, did you add `twitch.tv##+js(twitch-videoad)`? If you are not seeing any messages in the console then the script is not being loaded for some reason. First step would be to double check your config. Perhaps the link to the script needs to be updated on your end?

Yes I have. I've managed to make it work by switching to vaft, not sure why video-swap-new won't load properly though.

**Comment by pixeltris** [comment] 2024-06-15 21:37
Closing as I can't reproduce. userscript version is always recommended.

**Closed by pixeltris** 2024-06-15 21:37 UTC
