### ISSUE TITLE
scripts prevent frankerfacez from loading on firefox

### ISSUE THREAD

**Issue by yvawt** [pixeltris/TwitchAdSolutions#249] opened 2024-05-03 06:27 UTC
i've tested both scripts - video-swap-new and vaft in two different userscript managers - violentmonkey and tampermonkey, as well as using ublock origins userresource - and both scripts will prevent frankerfacez from loading when you middle click a stream or right click -> open in new tab - if the firefox setting "When you open a link, image or media in a new tab, switch to it immediately" is disabled - if the setting is enabled frankerfacez loads fine, or if you open in a new window instead of tab it also loads fine. i've tested both scripts and they allow frankerfacez to load fine on edge.

**Comment by Chway** [comment] 2024-05-09 16:06
Any news on this? I have a similar issue with video-swap-new + Frankerfacez, with FFZ refusing to load when opened in the background, I can't reproduce it consistently tho. But USUALLY, when in a game section, If I open multiple streams using the middle click to send them in the background, the first tab opened will failed to load FFZ, while it will load fine on the others. It can happen too when opening streams from a popup of an extension that I have made, in the background or not, but again, not always. Indeed, FFZ seems to load fine without video-swap-new and I have no issue when using Brave.

The only line that could be interesting  in the devtools console is **Error: page.tabs[tab.id] is undefined undefined**, which seems to appear only when FFZ failed to load. I could share all the messages but I'm not quite sure if everything is safe to share.

**Comment by pixeltris** [comment] 2024-06-15 21:17
This synchronous call causes it:

https://github.com/pixeltris/TwitchAdSolutions/blob/c66faba74ff1a8f5dec29c3716276f54c596fdc9/video-swap-new/video-swap-new.user.js#L126-L131

ttv-lol-pro also does the same synchronous call https://github.com/younesaassila/ttv-lol-pro/blob/e2aed80ff90d933f3a4af80684f8bbb51429400e/src/page/page.ts#L55-L57

I can't tell you why it results in FFZ failing to load. Unfortunately due to the way that code works it has to be a synchronous call. A simple fix is to provide a fixed url but this url would need to be updated frequently:

```js
    function getWasmWorkerUrl(twitchBlobUrl) {
        return 'https://assets.twitch.tv/assets/amazon-ivs-wasmworker.min-cd1fea52c5079942d599.js';
    }
```

**Comment by pixeltris** [comment] 2024-06-15 21:50
Yea that would work. Is that an auto updated mirror or manually updated @besuper?

**Comment by pixeltris** [comment] 2024-06-16 05:54
Fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/2eefb984c10ba64e9528b8cf4350d5fab653bd3a by moving the synchronous call into inside the worker itself.

**Closed by pixeltris** 2024-06-16 05:54 UTC
