### ISSUE TITLE
Script has Stopped Working

### ISSUE THREAD

**Issue by gzuzz187** [pixeltris/TwitchAdSolutions#260] opened 2024-06-11 21:53 UTC
The script isnt working anymore(3-4 weeks). Can someone hep me?

**Comment by smjkh** [comment] 2024-06-12 17:20
Mine just stopped working as well

**Comment by petercunha** [comment] 2024-06-13 02:29
+1 any fixers in chat

**Comment by stevenya97** [comment] 2024-06-13 16:28
Have you tried the suggestions over on #252 ? Mainly, try reverting uBo scripts and try out the userscript versions with TamperMonkey/ViolentMonkey. uBo is having some known issues loading the script in random cases(#200). You should be able to check the web console for `blocking ads` messages that indicate the script is running, if not appearing then likely uBo is not loading the script properly

**Comment by orangoz1** [comment] 2024-06-14 21:06
for me what fixed it was turning on developer mode it seemed chrome automatically by default turned it off.

**Comment by pixeltris** [comment] 2024-06-15 21:37
Closing as I can't reproduce. userscript version is always recommended.

**Closed by pixeltris** 2024-06-15 21:37 UTC

**Comment by petercunha** [comment] 2024-06-19 18:35
Turning off Enhanced Browsing Protection in Chrome and switching to video-swap-new fixed it for me
