### ISSUE TITLE
constant twitch video errors (Error #1000)

### ISSUE THREAD

**Issue by a-mad-dragon** [pixeltris/TwitchAdSolutions#228] opened 2024-03-18 19:19 UTC
Repeatedly getting "The video download was cancelled. Please try again. (Error #1000)" after only a few seconds only when one of the ublock scripts is active

**Comment by Chassss** [comment] 2024-03-18 19:22
yup seems like twitch updated something on there end about 40 minutes to an hour ago

**Comment by pixeltris** [comment] 2024-03-18 22:03
I can't reproduce but I'll keep an eye out for it.

**Comment by JTJutajoh** [comment] 2024-03-18 23:09
I've also been getting this for most of the day, though sometimes instead of an error I get an ad playing, #225 
I've used all three versions of both vaft and video-swap-new and still getting the same issue with all combinations.

**Comment by ClayBCE** [comment] 2024-03-22 12:33
Yep, I am also now getting ads and errors on all versions. Seems none of it is working anymore.

**Comment by Azaius0** [comment] 2024-03-25 22:29
Every time a midroll plays it goes to the same error for me. Also, when I click the "reload player" button the quality stays low until I refresh the page even after the blocked ad break finishes.

**Comment by racewarkingdoms** [comment] 2024-03-26 02:41
> Every time a midroll plays it goes to the same error for me. Also, when I click the "reload player" button the quality stays low until I refresh the page even after the blocked ad break finishes.

yep, exact same issue here, has made twitch nearly unusable these last 3-4 days

**Comment by lyricalcasanova** [comment] 2024-03-26 02:50
> > Every time a midroll plays it goes to the same error for me. Also, when I click the "reload player" button the quality stays low until I refresh the page even after the blocked ad break finishes.
> 
> yep, exact same issue here, has made twitch nearly unusable these last 3-4 days

Anyone found a fix for this yet? I have found only manually refreshing changes the quality even if I try to change quality in the player it stays low

**Comment by pixeltris** [comment] 2024-03-26 03:02
I haven't noticed this still with prerolls. I've been watching Twitch very casually lately so I haven't seen any midrolls. If this is a midroll only issue I can try sticking around some streams and look into it.

**Comment by Azaius0** [comment] 2024-03-26 03:12
Yeah it doesn't happen with prerolls and it's hard to know when a midroll will hit.

**Comment by placchio** [comment] 2024-03-31 12:59
Im also having the same issue and im using an old permalink of the script (i think a vaft from nov 2022?maybe earlier?) that never showed me an ad. I mean it still works at blocking ads but now i get this "#1000 error" on every stream. 
They managed to break all the versions...

**Comment by ragepyre** [comment] 2024-03-31 13:42
same started happen to me today, its not even only midrolls, when it try to block the ad, it drops connection and need to reload the player

**Comment by racewarkingdoms** [comment] 2024-04-07 01:35
any update on this?

**Comment by ragepyre** [comment] 2024-04-07 08:53
fixed now

**Comment by racewarkingdoms** [comment] 2024-04-09 23:50
negative, still broken for me

**Comment by lyricalcasanova** [comment] 2024-04-10 08:13
### At this time all ads are being blocked as expected
*(with low image quality during ads)*
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/33468668/2cad3fb3-9711-4507-9674-625505b1dc33)
**Operating System (OS)**
Windows 11 Pro Version 23H2
**Browser**
Google Chrome Version 123.0.6312.106 (Official Build) (64-bit)

**Setup**
[uBlock Origin Extension](https://ublockorigin.com/)
in "My Filters"
`twitch.tv##+js(twitch-videoad)`
in "Advanced Settings" for `userResourcesLocation` (Must click the checkbox for "I am an advanced user" and then the ⚙️ icon)
`https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/video-swap-new/video-swap-new-ublock-origin.js`

**Comment by pixeltris** [comment] 2024-04-10 12:45
I've checked streams every now and again. I still haven't had it happen to me on prerolls and I haven't seen a single midroll. Maybe it triggers more often with a Twitch account, I currently use the website without an account. I'll try with to see if it's any different.

**Comment by ClayBCE** [comment] 2024-04-10 13:05
I'm not sure how relevant this is, but for anyone who may be having issues:
I had been using an older link that was originally provided here (not sure if it changed at all?), but I ended up replacing it with the 'video-swap-new' u-block filter link (which was different than what I used to use from awhile back) and have since had the issue resolved.

**Comment by lyricalcasanova** [comment] 2024-04-10 13:06
> I've checked streams every now and again. I still haven't had it happen to me on prerolls and I haven't seen a single midroll. Maybe it triggers more often with a Twitch account, I currently use the website without an account. I'll try with to see if it's any different.

Just wanted to note I stay logged in 24/7 and leave twitch open on another monitor and never see ads anymore and don't see the "#1000 error" with the setup as mentioned above I do also have an auto refresh plugin that if a streams errors it auto reloads but I barely ever see it reload unless there are network issues with the actual stream

[Extension for auto reload link](https://chromewebstore.google.com/detail/automatic-twitch-drops-mo/kfhgpagdjjoieckminnmigmpeclkdmjm) (Chrome)
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/33468668/e8a396a7-2941-4366-a2ab-4d74fc915c58)

**Comment by TsukiZero** [comment] 2024-04-30 22:23
I'm suspicious it may have something to do with cookies as well, because at one point there were streams that would only open on Private Tabs, but they started working on normal tabs after clearing the cookies for Twitch and logging back in.

**Comment by SixelAlexiS90** [comment] 2024-05-14 09:27
This issue seems to be back, anyone else?

**Comment by Kotaless** [comment] 2024-05-14 09:34
> This issue seems to be back, anyone else?

Unfortunately, yes.

**Comment by ragepyre** [comment] 2024-05-14 09:37
lol it just came back like a nightmare

**Comment by Keula** [comment] 2024-05-14 10:10
Clearing cookies maybe helped(resets ffz though, mildly annoying), was infinite reload loop before and seemingly now working, still got the error twice, but the reload worked instantly, hard to say how long/if it'll stay though.

**Comment by Kotaless** [comment] 2024-05-14 12:47
I didn't clear anything or relogged in but it's fine now. I hope Twitch not working on breaking it completely.

**Comment by Liuzah** [comment] 2024-05-25 09:33
hi, still happening to me, i clear cookies for twitch but nothing, any solution? ty

**Comment by kioshimushi** [comment] 2024-06-10 14:46
I'm also getting it lattely. It seems that the Error #1000 appears after the preroll ads, when the script is supposed to reload the player just after the "blocking ads" message in the top left corner (although I don't see this message anymore when it happens)

**Comment by zentrextrov** [comment] 2024-06-12 11:46
> I'm also getting it lattely. It seems that the Error #1000 appears after the preroll ads, when the script is supposed to reload the player just after the "blocking ads" message in the top left corner (although I don't see this message anymore when it happens)

also getting this too

**Comment by stevenya97** [comment] 2024-06-13 16:30
Does the stream start playing again if you manually hit the "Reload Player" button in the video player? Or does the message persist?

**Comment by TsukiZero** [comment] 2024-06-13 20:14
most cases, yes, reloading the player resumes it, but is annoying to do it 100% manually. I use the userscript [Twitch Helper](https://greasyfork.org/en/scripts/445835-twitch-helper) to do it automatically instead.

**Comment by MonfGeiger** [comment] 2024-06-14 14:11
oh my god i swear this is annoying. been getting them so damn much lately that i thought my internet was on the fritz, but the second i turn my "video-swap-new" userscript off and reload, everything runs fine? I hope the userscripts can (somehow) be updated to combat this, and yes, i do have the needed ublock static filters to compliment the userscript in question

**Comment by pixeltris** [comment] 2024-06-15 19:21
Should be fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/644ac7a8217880597db52b506ae4d3ded287bedc

**Closed by pixeltris** 2024-06-15 19:21 UTC
