### ISSUE TITLE
Video Ad-Block twitch is not working 03/09/22

### ISSUE THREAD

**Issue by Hoffman93** [pixeltris/TwitchAdSolutions#97] opened 2022-09-03 19:58 UTC
It worked for me for months (firefox) but today it stopped working, I got ads, I restored ublock and added the script again, but I still see ads, cheers.

**Comment by Proaxel** [comment] 2022-09-06 18:51
The 480p method that it uses was patched. A few days ago Pixeltris updated it with the option to use the proxy method instead, but it is not enabled by default. Have you tried one of these?
![image](https://user-images.githubusercontent.com/9545347/188715220-d2c678d7-7314-4ae0-aa0b-d56e131a0b25.png)

**Comment by pixeltris** [comment] 2022-09-08 18:00
I'll keep an eye out but I'm closing this for now as I can't reproduce at the moment. It should be noted that you shouldn't see ads even if all methods fail. You should see a "Commercial break in progress" screen instead. If you see ads something may be conflicting.

**Closed by pixeltris** 2022-09-08 18:00 UTC
