### ISSUE TITLE
(Video Swap New) Incorrect Quality after ad

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#165] opened 2023-06-17 00:11 UTC
The player switches to 360p after "blocking ads" and doesn't revert to whatever was the default quality

**Comment by pixeltris** [comment] 2023-06-17 00:44
Duplicate of https://github.com/pixeltris/TwitchAdSolutions/issues/156

**Closed by pixeltris** 2023-06-17 00:44 UTC
