### ISSUE TITLE
Commercial Break on Chrome

### ISSUE THREAD

**Issue by Nerxxy** [pixeltris/TwitchAdSolutions#127] opened 2022-12-09 20:43 UTC
![image](https://user-images.githubusercontent.com/37718547/206792603-6d2c956d-a658-4c38-8c3f-2ff77310baf7.png)

Chrome version: Version 108.0.5359.99 (Official Build) (64-bit)

Windows 10 OS Build 19045.2311 22H2

**Comment by stevenya97** [comment] 2022-12-09 20:49
Are you using video-swap-new script? If so that is intended, you will see the commercial graphic but no ad.

**Comment by Nerxxy** [comment] 2022-12-09 21:02
@stevenya97 no im using the vaft [permalink](https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/338dadc691551a3ed3a82c2e336f59072e6d7167/vaft/vaft-ublock-origin.js)

**Comment by pixeltris** [comment] 2022-12-11 08:28
Duplicate of #114

**Closed by pixeltris** 2022-12-11 08:28 UTC
