### ISSUE TITLE
getting ads again

### ISSUE THREAD

**Issue by Dathmaker3** [pixeltris/TwitchAdSolutions#246] opened 2024-05-02 17:01 UTC
ive been getting ads again since yesterday  and no matter what i do i cant stop them

**Comment by stevenya97** [comment] 2024-05-02 17:28
Able to give any more details? Which solution are you using? (vaft or video-swap-new? ublock or userscript? proxy methods?)

**Comment by Dathmaker3** [comment] 2024-05-02 17:30
i am using vaft  and i belive userscript  i am new to this stuff so im not really sure

**Comment by stevenya97** [comment] 2024-05-02 19:52
No worries, let's walkthrough some steps to make sure everything is configured correctly. Are you using the latest 8.0.0 version of the script? If you are using a userscript manager like Tampermonkey, you should be able to view that information in its dashboard. Should be able to access that near the URL bar in your browser
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/10717304/0dcf03c9-2b15-42f1-8889-8aef10dca52d)
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/10717304/515bc469-3624-43a8-8b8c-0ee470fb4aba)

**Comment by Dathmaker3** [comment] 2024-05-02 19:55
it is 8.0.0

**Comment by whaaaley** [comment] 2024-05-03 06:26
i've been getting ads this week as well after it was previously working

**Comment by xunkar** [comment] 2024-05-04 15:21
Indeed, Twitch must have done something. I'm using video swap new with uBlock and ads started popping again a couple days ago.

**Comment by dsnvwlmnt** [comment] 2024-05-05 18:35
Just updated to the most recent vaft permalink. Still getting ads after closing and opening Brave.

**Comment by whaaaley** [comment] 2024-05-09 18:05
It definitely depends on the stream. It's very inconsistent.

**Comment by stevenya97** [comment] 2024-06-01 23:03
#252 has some suggestions for those still experiencing issues

**Comment by pixeltris** [comment] 2024-06-15 21:36
Closing as I can't reproduce. userscript version is always recommended.

**Closed by pixeltris** 2024-06-15 21:36 UTC
