### ISSUE TITLE
Vaft and video-swap-new pausing after midrolls

### ISSUE THREAD

**Issue by Medivha** [pixeltris/TwitchAdSolutions#187] opened 2023-10-02 15:32 UTC
Vaft and Video-Swap-new userscript on tampermonkey with firefox 117.0.1 (addons:frankerfacez + ublock origin)
works fine on the first midroll, but on the second it gets stuck on a loading screen. And you have to wait till ads are gone and it automatic refreshes or manually press pause->play and you see the blocking ads on top and refreshes automatic after wards but next midroll it gets stuck again.
this is buggy for a long time now i i'm just sick of ttv lol pro(because doesn't work 70% of time) and same for other proxy solutions, so i got back to this.
 just a automatic pause play would be nice?! or find another fix ;)

**Comment by pixeltris** [comment] 2023-10-02 16:16
Also probably a duplicate of #175

**Comment by Medivha** [comment] 2023-10-02 16:24
im testing right now without FrankerFaceZ and got first ad so still waiting for second. but it interesting that without FFZ it runs on low res while the ad runs but with FFZ it runs on source res when the ad runs

**Comment by Medivha** [comment] 2023-10-02 16:58
finally second ad and it is working so it is something with FFZ.

**Comment by Medivha** [comment] 2023-10-14 15:06
1-2 Days later of my previous post, a lot of People noticed they don't got ads any more. Not related to the script including me so I stopped looking for a solution for now until it breaks again for me(hard to test without getting ads  ;)  and also i have no clue what i'm doing).
germany, firefox, tampermonkey, ublock origin, video swap new script(not VAFT). for my setup. but it depends on location and whatever random setup you have.
If you use chrome just don't. You will have it 10 times harder to fight against ads.

good luck finding a solution for you

**Comment by Medivha** [comment] 2023-10-17 01:57
Germany is normally super AD heavy. idk what twitch is doing

why would a German browser extension from a german guy living in germany phone "home" to russia????
and i dont even see anything about that in the Privacy policy

**Comment by EchoDev** [comment] 2023-11-05 20:51
Potential fix in #199

If someone wants to test it to confirm, this fixed the issue on my end.

**Comment by pixeltris** [comment] 2024-06-15 21:53
Consolidating all freezing / pausing / playback issues for `vaft` into #164 

`video-swap-new` generally shouldn't suffer from the same playback issues but if you're having playback issues see #119

**Closed by pixeltris** 2024-06-15 21:53 UTC
