### ISSUE TITLE
script stopped working

### ISSUE THREAD

**Issue by Skuyt2** [pixeltris/TwitchAdSolutions#239] opened 2024-04-12 02:10 UTC
The vaft script for tampermonkey stopped working, I already reinstalled it but without success I believe an update came on Twitch and ended up taking down the script, please update.

**Comment by Dark-Dragon** [comment] 2024-04-12 02:30
From what it seems some channels have transitioned over to different means of ad-delivery. I'm still blocking ads fine on a lot of channels, just not all. Using video-swap-new (ublock).

**Comment by Skuyt2** [comment] 2024-04-12 03:23
I've already tried using swap in ublock origin too, but the AD is still appearing, I think it's a deal and waiting to update the script

**Comment by stevenya97** [comment] 2024-04-12 03:50
Some more details in #236 . Pixeltris has already replied with an update, he is looking into an issue with the workers hooking functionality which is causing the script to not work atm. Seems to be a Twitch server side change

**Comment by pixeltris** [comment] 2024-04-12 11:51
Duplicate of #236

**Closed by pixeltris** 2024-04-12 11:51 UTC
