### ISSUE TITLE
Just tried to ad this and need help

### ISSUE THREAD

**Issue by whatsmyageagain182** [pixeltris/TwitchAdSolutions#280] opened 2024-09-10 00:49 UTC
Hello, iv pretty much only installed uBo and let it do its thing. Iv been getting some twitch ad's and with some google I found this github and it says I need to add something to my filters list, but I dont see a way to add something. Iv put the url under my userResourcesLocation, and its added under custom but its got error notifications, the yellow ! saying out of date, and a red chain link saying network error prevents it from updating.  What am I doing wrong ?
![ublock](https://github.com/user-attachments/assets/fe02e85a-8944-4701-902c-1be7c4ad23e4)
![ublock2](https://github.com/user-attachments/assets/d6fcd713-1e17-4a95-bc6f-db843f5ea68e)
![ub3](https://github.com/user-attachments/assets/368ae77c-e112-48e6-ab75-b7767c71cf17)

**Comment by whatsmyageagain182** [comment] 2024-09-10 01:11
So I was messing around and removed the link from the custom and now on twitch I get the blocking mid roll ads, but my video quality goes to like 160p lol

**Comment by stevenya97** [comment] 2024-09-10 17:53
That is intended, the only video stream available during ads is a low quality one, often used to display above Twitch chat as a muted stream preview during ads. Quality of the secondary stream ranges from 160p-480p typically. Ads are inserted into the full quality stream itself and cannot be blocked directly. Thus the scripts switches from the main video stream with the ads banner to this secondary stream and resumes the normal full quality stream when ads are over. If you are seeing the `Blocking ads` banner in the top left of the player, things are working as intended.

If you have issues, please re-read the README again and follow all instructions. For uBlock version there are 2 main steps, which you've both done already: 1) loading the script into `userResourcesLocation`. 2) Adding the filter to `My filters`, you can copy paste it there and hit `Apply Changes`. You are right that you remove the link from `Filter lists` tab, that does not go there. 

If you have further playback or ad blocking issues, see the comment near the end of the README mentioning #200 . Userscript is recommended over uBlock version.

**Comment by whatsmyageagain182** [comment] 2024-09-10 18:42
> That is intended, the only video stream available during ads is a low quality one, often used to display above Twitch chat as a muted stream preview during ads. Quality of the secondary stream ranges from 160p-480p typically. Ads are inserted into the full quality stream itself and cannot be blocked directly. Thus the scripts switches from the main video stream with the ads banner to this secondary stream and resumes the normal full quality stream when ads are over. If you are seeing the `Blocking ads` banner in the top left of the player during ads things are working as intended.
> 
> If you have issues, please re-read the README again and follow all instructions. For uBlock version there are 2 main steps, which you've both done already: 1) loading the script into `userResourcesLocation`. 2) Adding the filter to `My filters`, you can copy paste it there and hit `Apply Changes`. You are right that you remove the link from `Filter lists` tab, that does not go there.
> 
> If you have further playback or ad blocking issues, see the comment near the end of the README mentioning #200 . Userscript is recommended over uBlock version.

thank you for the reply !

**Comment by stevenya97** [comment] 2024-09-10 20:36
Glad I could help! If you have no further issues, feel free to close this issue. You can re-open it or create a new one when you encounter an issue.

**Closed** 2024-09-11 21:31 UTC
