### ISSUE TITLE
TwitchAdSolutions (vaft) bugged

### ISSUE THREAD

**Issue by shepial** [pixeltris/TwitchAdSolutions#124] opened 2022-12-03 21:25 UTC
When you enter a stream and it has an initial announcement, it bugs and this image appears for minutes without being able to see anything else than that. Ty. [https://gyazo.com/19e234ff1643fa577b8f8f42fa622c03](url)

**Comment by pixeltris** [comment] 2022-12-03 21:29
Duplicate of #114

**Closed by pixeltris** 2022-12-03 21:29 UTC
