### ISSUE TITLE
VAFT is not working anymore

### ISSUE THREAD

**Issue by Zero3K** [pixeltris/TwitchAdSolutions#185] opened 2023-09-08 23:59 UTC
*subject*

**Comment by brasqo** [comment] 2023-09-09 03:31
I can verify this.

**Comment by JasperKazai** [comment] 2023-09-09 06:58
Yep, it's currently not working for me either. Either seeing ads or the "stream is being set up" Twitch screen for the full duration of ad breaks. Refreshing and whatnot does not bypass this.

**Comment by revunix** [comment] 2023-09-09 07:16
We are beginning to know that it no longer works... just use TTV LOL PRO with a proxy.

**Comment by pixeltris** [comment] 2023-09-09 08:19
Probably the same as #181. They could be A/B testing. I'm currently not observing this for prerolls. I'll take a look when I do.

**Comment by JasperKazai** [comment] 2023-09-09 21:55
It seems to be working again. At least it is for me right now. Still has the pausing/buffering issue, but that's better than having ads.

**Comment by bshener** [comment] 2023-09-10 03:33
still not working

**Comment by kennycontreras** [comment] 2023-09-30 17:02
It's a similar case for other ad blocks. So, it may be that Twitch found something to bypass the plugin.

**Comment by Zero3K** [comment] 2023-09-30 17:11
It is now working most of the time.

**Comment by Mrcubix** [comment] 2023-10-04 20:45
FFZ is breaking it somehow, disabling the extension fixes it

**Comment by pixeltris** [comment] 2023-10-11 10:17
Closing as I still can't reproduce this.

In https://github.com/pixeltris/TwitchAdSolutions/commit/a285eeda5046a304c5eb38b958c875afca066daa I fixed an edge case where the player would sometimes get stuck on a black screen / infinite loading when opening a stream. But if you actually see ads then it's an issue with the script being applied.

**Closed by pixeltris** 2023-10-11 10:17 UTC
