### ISSUE TITLE
Vaft / New ad block broken as of  7/20/24

### ISSUE THREAD

**Issue by Xelor41023** [pixeltris/TwitchAdSolutions#268] opened 2024-07-21 04:06 UTC
It seems twitch updated there services so the block is no longer working and am being served ads again  I am using brave nightly  with tampermonkey with the userscripts applied

**Comment by Xelor41023** [comment] 2024-07-22 14:31
<img width="1243" alt="image" src="https://github.com/user-attachments/assets/c9a3844b-ef77-402a-952f-ec622e15097e">

**Comment by stevenya97** [comment] 2024-07-22 18:46
Which script do you have loaded? It should only be one enabled, having both can conflict with each other. Do you have any other twitch related extensions?

**Comment by Xelor41023** [comment] 2024-07-23 04:36
I tested  it with  only vaft and  ad block swap new  enabled bolth cases still got ads. no other ads that would  interfere with twitch are installed.

**Comment by JaredBanks** [comment] 2024-07-23 05:19
+1 , also having ads since 2-3 days ago.

Using only 1 script with is the master vaft:
https://github.com/pixeltris/TwitchAdSolutions/blob/master/vaft/vaft-ublock-origin.js

Made sure that I have the filter:
twitch.tv##+js(twitch-videoad)

**Comment by Drudo25** [comment] 2024-07-23 16:30
Was having the same issue with both scripts. I switched over to the AdGuardExtra solution in the mean time and it seemed to be working for now.

**Comment by Suprcheese** [comment] 2024-07-23 17:32
Having issues as well with both vaft and video-swap-new, using uBlock origin and Firefox.

**Comment by Xelor41023** [comment] 2024-07-26 02:18
AdGuardExtr also seems to be broken as well

**Comment by Hebes24** [comment] 2024-07-31 20:17
Any word on this getting fixed?

**Comment by revunix** [comment] 2024-07-31 21:13
> Any word on this getting fixed?

Yes, use TTV LOL PRO with a Estland or China [Proxy](https://proxy6.net/en/?r=467594)! This still works and didn't need a fix...

**Comment by javilink** [comment] 2024-08-02 02:10
> > Any word on this getting fixed?
> 
> Yes, use TTV LOL PRO with a Estland or China [Proxy](https://proxy6.net/en/?r=467594)! This still works and didn't need a fix...

Hello. 

     What version of the TTV LOL PRO extension are you using? the V1 or V2? Could you put the linf or URL of the proxies that are working for you?

Greetings and thank you very much!

**Comment by zGato** [comment] 2024-08-02 10:49
@javilink he's just advertising his affiliate link for you to buy your own proxy.

TTV LOL PRO V1 is deprecated and not supported, won't work for most people, and not recommended for non-advanced users.
TTV LOL PRO V2 is supported and updated frequently, although if you don't want to deal with commercial break in progress, you'll need to purchase your own proxy / support the project.

**Comment by DaruniasJoy** [comment] 2024-08-02 11:22
Reinstalling Ublock and reapplying Vaft Ublock Permalink did seem to fix the issue for me.

At least now i do get the "blocking ads" Prompt and stream does not get interrupted by that.

**Comment by stevenya97** [comment] 2024-08-02 16:47
For `vaft/video-swap-new` users, please follow the troubleshooting tips under #267 . That thread has methods for detecting if the ads are being actively detected by the script. Most of the tips still apply: Toggle uBo extension off/on to force fetching of the script url, double check uBlock script url/filter. Userscript version is recommended over uBlock scripts(known issues with uBlock #200 ), revert uBlock scripts/filters, don't use multiple blocker methods together(i.e. `vaft` & `AdGuardExtra`), stick to using one userscript(i.e. just `vaft` not `vaft`+`video-swap-new` both enabled). If you are being served ads, the scripts are not running properly in your setup. If you are having stream freezing/playback issues with vaft, you are possibly using multiple blocking methods that are interfering with each other. #164 tracks all other vaft issues. `AdguardExtra` code is very similar to `vaft` so it should function the same if you prefer it. Still recommended to use uBlock for non-video stream banner ads found on the rest of the page.

**Comment by pixeltris** [comment] 2024-08-06 03:13
Going to close this one as I can't reproduce. Maybe they are doing a long A/B test but it seems doubtful.

**Closed by pixeltris** 2024-08-06 03:13 UTC
