### ISSUE TITLE
Ads slipping through Video Swap

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#181] opened 2023-09-02 12:21 UTC
Yep, again. At this point it might be wise of me to look into ways to run the phone app on PC with Blokada 2 and isolate the chat in a popup. It's hopeless

**Comment by Sylaeya** [comment] 2023-09-05 05:31
Yeah, I just had a pre-roll add play on a stream. Using Video-Swap-New on Chrome (v 116.0.5845.141). Had been working fine since the last update.

**Comment by pixeltris** [comment] 2023-09-05 13:28
I'm going to close this as I can't reproduce this issue.

@Sylaeya that might be related to this #29. Sometimes the script would stop being applied for no logical reason under uBlock Origin. I use the userscript version where the bug doesn't happen.

**Closed by pixeltris** 2023-09-05 13:28 UTC

**Comment by TsukiZero** [comment] 2023-09-05 14:28
I'm using Userscript as well, so...

**Comment by Sylaeya** [comment] 2023-09-05 22:41
@pixeltris Thanks so much for the info. I installed the Video-Swap-New userscript with TamperMonkey and can confirm its working properly for me at this time.

**Comment by DaveKap** [comment] 2023-09-07 23:28
Just wanted to add that by removing the script from uBlock Origin, applying changes, then re-adding it, it began working again.
