### ISSUE TITLE
[Question] Ublock solution infinite loading

### ISSUE THREAD

**Issue by DannyDarth** [pixeltris/TwitchAdSolutions#24] opened 2021-04-03 02:45 UTC
Why does the Ublock solution cause the stream to infinitely load for me when it tries to play an ad?

**Comment by KillaBoi** [comment] 2021-04-03 03:20
refresh and it'll start working, for some reason u need to refresh after an ad starts and it doesnt instantly switch to the 480p stream :/

**Comment by DannyDarth** [comment] 2021-04-03 03:27
aw thats kinda lame :/

**Comment by pixeltris** [comment] 2021-04-03 06:44
Could you be more specific as to which solution you're using?

`notify-reload` by design reloads until there aren't ads, but that can backfire and result infinite reloads.

**Comment by DannyDarth** [comment] 2021-04-03 06:59
Hey sorry im using the ublock solution below:

`Applying a solution (uBlock Origin)

    Navigate to the uBlock Origin Dashboard (the extension options)
    Under the My filters tab add twitch.tv##+js(twitch-videoad).
    Under the Settings tab, enable I am an advanced user, then click the cog that appears. Modify the value of userResourcesLocation from unset to the full url of the solution you wish to use (if a url is already in use, add a space after the existing url). e.g. userResourcesLocation https://github.com/pixeltris/TwitchAdSolutions/raw/master/notify-strip/notify-strip-ublock-origin.js
    To ensure uBlock Origin loads the script I recommend that you disable/enable the uBlock Origin extension (or restart your browser).
`

**Comment by pixeltris** [comment] 2021-04-03 07:04
Yes `notify-strip` shouldn't reload the player, so there's a bug there.

Does it happen on every stream? Which browser do you use? What does the "reload" look like? Perhaps you could take a video of it?

**Comment by DannyDarth** [comment] 2021-04-03 07:14
I use mozilla, when i reload its at a very low res but goes back to 1080p or whatever source is after a little bit. As for a video i cannot. It happens on all streams. Especially streams that have loads of ads very often.

**Comment by pixeltris** [comment] 2021-04-03 07:19
So `notify-strip` as described in the README plays a low resolution stream (360p, or 480p, I forget) for the duration of the ad.

The script itself shouldn't cause any unnatural reloads, if that happens then there is a bug. But the low resolution is expected.

If there are more ads (low resolution) occurrences than without the script when browsing streams, then there's a bug with notify Twitch that ads were watched, and that needs to be addressed (sometimes this feels this is the case, but I currently don't have concrete proof). Additionally an ad isn't accepted as "watched" by Twitch until the ad banner goes away.

**Comment by DannyDarth** [comment] 2021-04-03 07:40
Gotcha hopefully you can fix the bug, if it is a bug. The infinite loading wheel does accrue sometimes. I just had it happen to me. Might be due to loss of focus when looking at a different mozilla tab for a bit.

**Comment by pixeltris** [comment] 2021-04-11 23:17
It looks like midroll ads are broken and a loading wheel will display until the stream is restarted (e.g. pause/play). I'm not sure if this happens 100% of the time.

To be clear about the original issue, you get the loading wheel on both preroll and midroll ads? Or just midroll ads?

**Comment by DannyDarth** [comment] 2021-04-11 23:29
> 
> 
> It looks like midroll ads are broken and a loading wheel will display until the stream is restarted (e.g. pause/play). I'm not sure if this happens 100% of the time.
> 
> To be clear about the original issue, do you get the loading wheel on both preroll and midroll ads? Or just midroll ads?

It happens during a stream. not at the start.

**Comment by pixeltris** [comment] 2021-04-11 23:33
Ok great thanks for the info. That seems to align up with a couple of comments on reddit too. I'll try and look into the midroll ad issues when I get the chance.

It might be worth trying this version which uses a different algorithm (less smooth 480p->src resolution transition, but possibly less likely to have issues such as midroll issues) https://github.com/pixeltris/TwitchAdSolutions/tree/c3e1ee390ae684fe47d5159c689332d53e67094d/notify-strip

**Comment by DannyDarth** [comment] 2021-04-12 00:23
> 
> 
> Ok great thanks for the info. That seems to align up with a couple of comments on reddit too. I'll try and look into the midroll ad issues when I get the chance.
> 
> It might be worth trying this version which uses a different algorithm (less smooth 480p->src resolution transition, but possibly less likely to have issues such as midroll issues) https://github.com/pixeltris/TwitchAdSolutions/tree/c3e1ee390ae684fe47d5159c689332d53e67094d/notify-strip

Thanks man it works pretty good other than that issue. Oh and say you have the stream muted and go to another tab... or just go to another tab for a little bit it will do the loading wheel aswell. Not sure if thats avoidable though.

**Comment by pixeltris** [comment] 2021-06-12 04:43
This should hopefully be fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/f37af091928cc4c93375047d72195aae4b31e4bd if the issue persists feel free to reopen this.

**Closed by pixeltris** 2021-06-12 04:43 UTC
